In [1]:
import pandas as pd
import pymongo

df = pd.read_csv('data.csv')
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [5]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\envs\vehicle\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\envs\vehicle\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.3 MB 670.4 kB/s eta 0:00:17
   - -------------------------------------- 0.5/11.3 MB 670.4 kB/s eta 0:00:17
   - -------------------------------------- 0.5/11.3 MB 670.4 kB/s eta 0:00:17
   - -------------------------------------- 0.5/11.3 MB 670.4 kB/s eta 0:00:17
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.3 MB 486.4 kB/s eta 0:00:22
   --- ------------------------------------ 1.0/11.3 MB 306.8 kB/s eta 0:00:34
   --- ------------------------------------ 1.0/11.3 MB 306.8 kB/s eta 0:00:34
   --- ------------------------------------ 1.0/11.3 MB 306.8 kB/s eta 0:00:34
   ---- ----------------------------------- 1.3/11.3 MB 327.4 kB/s eta 0:00:31
   ---- ----------------------------------- 1.3/11.3 MB 327.4 kB/s eta 0:00:31
   ----- ---------------------------------- 1.6/11.3 MB 356.9 kB/s eta 0:00:28
   ----- ---------------------------------- 1.6/11.3 MB 356.9 kB/s eta 0:00:28
   ------ --------------------------------- 1.8/11.3 MB 382.7 kB/s eta 0:00:25
   ------ --------------------------------- 1.8/11.3 MB 382.7 kB/s eta 0:00:25
   ------ --------------------------------- 1.8/11.3 MB 382.7 kB/s eta 0:00:25
   ------- -------------------------------- 2.1/11.3 MB 396.8 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/11.3 MB 396.8 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/11.3 MB 407.9 kB/s eta 0:00:23
   -------- ------------------------------- 2.4/11.3 MB 407.9 kB/s eta 0:00:23
   --------- ------------------------------ 2.6/11.3 MB 420.6 kB/s eta 0:00:21
   --------- ------------------------------ 2.6/11.3 MB 420.6 kB/s eta 0:00:21
   --------- ------------------------------ 2.6/11.3 MB 420.6 kB/s eta 0:00:21
   --------- ------------------------------ 2.6/11.3 MB 420.6 kB/s eta 0:00:21
   ---------- ----------------------------- 2.9/11.3 MB 417.4 kB/s eta 0:00:21
   ---------- ----------------------------- 2.9/11.3 MB 417.4 kB/s eta 0:00:21
   ----------- ---------------------------- 3.1/11.3 MB 424.2 kB/s eta 0:00:20
   ----------- ---------------------------- 3.1/11.3 MB 424.2 kB/s eta 0:00:20
   ----------- ---------------------------- 3.1/11.3 MB 424.2 kB/s eta 0:00:20
   ------------ --------------------------- 3.4/11.3 MB 427.4 kB/s eta 0:00:19
   ------------ --------------------------- 3.4/11.3 MB 427.4 kB/s eta 0:00:19
   ------------ --------------------------- 3.4/11.3 MB 427.4 kB/s eta 0:00:19
   ------------ --------------------------- 3.7/11.3 MB 431.0 kB/s eta 0:00:18
   ------------- -------------------------- 3.9/11.3 MB 449.1 kB/s eta 0:00:17
   -------------- ------------------------- 4.2/11.3 MB 467.8 kB/s eta 0:00:16
   --------------- ------------------------ 4.5/11.3 MB 481.1 kB/s eta 0:00:15
   --------------- ------------------------ 4.5/11.3 MB 481.1 kB/s eta 0:00:15
   ---------------- ----------------------- 4.7/11.3 MB 489.2 kB/s eta 0:00:14
   ---------------- ----------------------- 4.7/11.3 MB 489.2 kB/s eta 0:00:14
   ----------------- ---------------------- 5.0/11.3 MB 501.7 kB/s eta 0:00:13
   ------------------ --------------------- 5.2/11.3 MB 513.3 kB/s eta 0:00:12
   ------------------ --------------------- 5.2/11.3 MB 513.3 kB/s eta 0:00:12
   ------------------ --------------------- 5.2/11.3 MB 513.3 kB/s eta 0:00:12
   ------------------- -------------------- 5.5/11.3 MB 510.7 kB/s eta 0:00:12
   ------------------- -------------------- 5.5/11.3 MB 510.7 kB/s eta 0:00:12
   -------------------- ------------------- 5.8/11.3 MB 517.3 kB/s eta 0:00:11
   --------------------- ------------------ 6.0/11.3 MB 523.5 kB/s eta 0:00:11
   --------------------- ------------------ 6.0/11.3 MB 523.5 kB/s eta 0:00:11
   ---------------------- ----------------- 6.3/11.3 MB 527.9 kB/s eta 0:00:10
   ---------------------- ----------------- 6.3/11.3 MB 527.9 kB/s eta 0:00:10
   ----------------------- ---------------- 6.6/11.3 MB 539.0 kB/s eta 0:00:09
   ----------------------- ---------------- 6.6/11.3 MB 539.0 kB/s eta 0:00:09
   ------------------------ --------------- 6.8/11.3 MB 541.9 kB/s eta 0:00:09
   ------------------------ --------------- 7.1/11.3 MB 549.4 kB/s eta 0:00:08
   ------------------------ --------------- 7.1/11.3 MB 549.4 kB/s eta 0:00:08
   ------------------------- -------------- 7.3/11.3 MB 552.4 kB/s eta 0:00:08
   ------------------------- -------------- 7.3/11.3 MB 552.4 kB/s eta 0:00:08
   ------------------------- -------------- 7.3/11.3 MB 552.4 kB/s eta 0:00:08
   -------------------------- ------------- 7.6/11.3 MB 550.1 kB/s eta 0:00:07
   -------------------------- ------------- 7.6/11.3 MB 550.1 kB/s eta 0:00:07
   -------------------------- ------------- 7.6/11.3 MB 550.1 kB/s eta 0:00:07
   -------------------------- ------------- 7.6/11.3 MB 550.1 kB/s eta 0:00:07
   --------------------------- ------------ 7.9/11.3 MB 532.9 kB/s eta 0:00:07
   --------------------------- ------------ 7.9/11.3 MB 532.9 kB/s eta 0:00:07
   --------------------------- ------------ 7.9/11.3 MB 532.9 kB/s eta 0:00:07
   --------------------------- ------------ 7.9/11.3 MB 532.9 kB/s eta 0:00:07
   ---------------------------- ----------- 8.1/11.3 MB 522.1 kB/s eta 0:00:07
   ---------------------------- ----------- 8.1/11.3 MB 522.1 kB/s eta 0:00:07
   ---------------------------- ----------- 8.1/11.3 MB 522.1 kB/s eta 0:00:07
   ---------------------------- ----------- 8.1/11.3 MB 522.1 kB/s eta 0:00:07
   ----------------------------- ---------- 8.4/11.3 MB 507.9 kB/s eta 0:00:06
   ----------------------------- ---------- 8.4/11.3 MB 507.9 kB/s eta 0:00:06
   ----------------------------- ---------- 8.4/11.3 MB 507.9 kB/s eta 0:00:06
   ----------------------------- ---------- 8.4/11.3 MB 507.9 kB/s eta 0:00:06
   ------------------------------ --------- 8.7/11.3 MB 499.9 kB/s eta 0:00:06
   ------------------------------ --------- 8.7/11.3 MB 499.9 kB/s eta 0:00:06
   ------------------------------- -------- 8.9/11.3 MB 502.4 kB/s eta 0:00:05
   ------------------------------- -------- 8.9/11.3 MB 502.4 kB/s eta 0:00:05
   ------------------------------- -------- 8.9/11.3 MB 502.4 kB/s eta 0:00:05
   -------------------------------- ------- 9.2/11.3 MB 501.3 kB/s eta 0:00:05
   -------------------------------- ------- 9.2/11.3 MB 501.3 kB/s eta 0:00:05
   --------------------------------- ------ 9.4/11.3 MB 501.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 501.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.3 MB 501.9 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 503.3 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 503.3 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 503.3 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 503.3 kB/s eta 0:00:04
   ---------------------------------- ----- 9.7/11.3 MB 503.3 kB/s eta 0:00:04
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.3 MB 486.9 kB/s eta 0:00:03
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.2/11.3 MB 157.6 kB/s eta 0:00:08
   ------------------------------------ --- 10.5/11.3 MB 122.9 kB/s eta 0:00:07
   ------------------------------------ --- 10.5/11.3 MB 122.9 kB/s eta 0:00:07
   ------------------------------------ --- 10.5/11.3 MB 122.9 kB/s eta 0:00:07
   ------------------------------------ --- 10.5/11.3 MB 122.9 kB/s eta 0:00:07
   ------------------------------------ --- 10.5/11.3 MB 122.9 kB/s eta 0:00:07
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   ------------------------------------- -- 10.7/11.3 MB 106.2 kB/s eta 0:00:06
   -------------------------------------- - 11.0/11.3 MB 97.9 kB/s eta 0:00:04
   -------------------------------------- - 11.0/11.3 MB 97.9 kB/s eta 0:00:04
   -------------------------------------- - 11.0/11.3 MB 97.9 kB/s eta 0:00:04
   -------------------------------------- - 11.0/11.3 MB 97.9 kB/s eta 0:00:04
   -------------------------------------- - 11.0/11.3 MB 97.9 kB/s eta 0:00:04
   ---------------------------------------  11.3/11.3 MB 97.2 kB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 99.2 kB/s  0:00:46
Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 840.2 kB/s eta 0:00:15
   - -------------------------------------- 0.5/12.9 MB 840.2 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.9 MB 657.8 kB/s eta 0:00:19
   -- ------------------------------------- 0.8/12.9 MB 657.8 kB/s eta 0:00:19
   --- ------------------------------------ 1.0/12.9 MB 645.1 kB/s eta 0:00:19
   --- ------------------------------------ 1.0/12.9 MB 645.1 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/12.9 MB 664.5 kB/s eta 0:00:18
   ---- ----------------------------------- 1.6/12.9 MB 705.1 kB/s eta 0:00:17
   ---- ----------------------------------- 1.6/12.9 MB 705.1 kB/s eta 0:00:17
   ----- ---------------------------------- 1.8/12.9 MB 694.4 kB/s eta 0:00:16
   ----- ---------------------------------- 1.8/12.9 MB 694.4 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.9 MB 699.0 kB/s eta 0:00:16
   ------ --------------------------------- 2.1/12.9 MB 699.0 kB/s eta 0:00:16
   ------- -------------------------------- 2.4/12.9 MB 688.3 kB/s eta 0:00:16

In [7]:
!pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [2]:
# df should be converted into dict before we push it to mongodb

data = df.to_dict(orient='records')
# data

In [3]:
DB_NAME = "Proj1"
COLLECTION_NAME = "Proj1-Data"
CONNECTION_URL = "mongodb+srv://rahulkr18499_db_user:MWnyL1pg1LxJ0Imq@cluster0.1vugtyr.mongodb.net/?appName=Cluster0"

# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github.

In [4]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [5]:
# Uploading data to MongoDB
rec = collection.insert_many(data)

In [6]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,69b9a7cd9768303b079be302,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,69b9a7cd9768303b079be303,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0

In [ ]:
## If you are getting timeout issue

# import certifi
# client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# # TO CREATE THE DATABASE
# data_base = client[DB_NAME]
# collection = data_base[COLLECTION_NAME]
# # TO INSERT DATA INTO THE COLLECTION
# rec = collection.insert_many(data)